### ISSUE TITLE
-bash: ti_recover: command not found

### ISSUE THREAD

**Issue by elkouriabdelali** [creador/ti_recover#1]
Hi plz how fix -bash: ti_recover: command not found

**Comment by creador** [comment]
Hi, You need a Mac to run the executable. If not, then remove the first line from ti_recover, install on a local directory and run 'node ti_recover'.

**Comment by elkouriabdelali** [comment]
:( he don't work

**Comment by elkouriabdelali** [comment]
![capture d ecran 2017-03-09 a 12 25 35](https://cloud.githubusercontent.com/assets/2196495/23750163/8fe36b2a-04c3-11e7-8f9b-7940852a4011.png)

**Comment by creador** [comment]
Thats because you need to edit the file named 'cli' (thats the one that runs when you write ti_recover). Remove the first line (the one that has the env/node) and run 'node cli'
In what operating system are you trying to run this package?

**Comment by elkouriabdelali** [comment]
![capture d ecran 2017-03-09 a 12 45 07](https://cloud.githubusercontent.com/assets/2196495/23750742/4cccac04-04c6-11e7-8e40-5e73f7c988dc.png)

**Comment by elkouriabdelali** [comment]
u can usse teamviewer plz

**Comment by creador** [comment]
I'm replying you from me phone, so i cant use teamviewer. I also run this code from MacOS Sierra and it works for me without making any chances. Did you install it using 'npm install -g' ? Also it needs java to be installed. What node version do u have?

**Comment by elkouriabdelali** [comment]
![capture d ecran 2017-03-09 a 15 04 07](https://cloud.githubusercontent.com/assets/2196495/23755882/b9b7f216-04d9-11e7-835c-b2bc9a7714a2.png)

**Comment by creador** [comment]
It can be 2 things:
1) you haven't 'installed' the package yet. You need to run the cmd 'sudo npm install ti_recover -g'
2) your node version. It was made for the v4.x version of node (32 bit). The v6 of node is 64 bits and untested.

Please tell me if number one is not the issue.
