### ISSUE TITLE
All good except my controllers 

### ISSUE THREAD

**Issue by Xefrok** [creador/ti_recover#4]
I installed ti_recover globally as you suggested, worrked perfectly, but now everything is recovered except the .js controllers

this is the error

`preparing -> ready
decoding bytes ...
converting into java array of bytes ... takes some time
extracting file ranges ...
file:alloy/CFG.js, decrypted !
file:app.js, decrypted !
file:alloy/backbone.js, decrypted !
file:alloy/constants.js, decrypted !
file:alloy/controllers/aviso.js, decrypted !
file:alloy/controllers/BaseController.js, decrypted !
file:alloy/controllers/cliente.js, decrypted !
file:alloy/controllers/cuenta.js, decrypted !
file:alloy/controllers/index.js, decrypted !
file:alloy/controllers/info.js, decrypted !
file:alloy/controllers/informacion.js, decrypted !
file:alloy/controllers/login.js, decrypted !
file:alloy/controllers/registro.js, decrypted !
file:alloy/styles/aviso.js, decrypted !
file:alloy/styles/cliente.js, decrypted !
file:alloy/styles/cuenta.js, decrypted !
file:alloy/styles/index.js, decrypted !
file:alloy/styles/info.js, decrypted !
file:alloy/styles/login.js, decrypted !
file:alloy/styles/registro.js, decrypted !
file:alloy/sync/localStorage.js, decrypted !
file:alloy/sync/properties.js, decrypted !
file:alloy/sync/sql.js, decrypted !
file:alloy/underscore.js, decrypted !
file:alloy/widget.js, decrypted !
file:alloy.js, decrypted !
file:ti.cloud/ti.cloud.js, decrypted !
file:_app_props_.json, decrypted !
C:\---USER----\AppData\Roaming\npm\node_modules\ti_recover\node_modules\mkdirp\index.js:90
                    throw err0;
                    ^

Error: EEXIST: file already exists, mkdir 'C:\---USER----\AppData\Roaming\npm\node_modules\ti_recover'`

Any suggestions?

**Comment by creador** [comment]
Most probably the output directory you put, already existed and it must not.

**Comment by Xefrok** [comment]
Man, i love you.
but im still a %#$$%" noob at nodejs

now i got this error
sorry, i understand if you dont reply, too much issues made by me.

> path.js:33
function normalizeStringWin32(path, allowAboveRoot) {
                             ^

RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:328:20)

**Comment by creador** [comment]
I would suggest you use a publicly accesible folder that doesn't need Admin mode for the output directory. The issue you are describing seems to be related to resolve the real output path for your Windows folder. I developed and tested this on a Mac, so i didn't take into account windows path resolving (example 'My Documents' folder is a virtual folder alias, not a real folder location), just generic path separation chars. Please reply if it works for you following this advice.
