### ISSUE TITLE
Add java/node requirements in the readme

### ISSUE THREAD

**Issue by Aryess** [creador/ti_recover#5]
Hi!

Could you please add the java and node versions you're using for this? I can't for the life of me get it to run. I used it once a year ago, and everything went fine, but now I have a new machine, can't get past the `node-gyp` rebuild phase on install. I've tried different versions of Java (8, 11, 12), and node but no success.

I've installed it locally and tried to bump the version of `node-java` in this package and `apk_unpack` to match my version of Java (11), and it's installing fine, but I'm getting a core dump on run.

Any help to replicate your setup would be appreciated.

Thanks!

**Comment by Aryess** [comment]
If anyone runs into the same issue, this worked for me:

```
workspace|⇒ node -v
v6.17.1
workspace|⇒ npm -v
3.10.10
workspace|⇒ javac -version
javac 1.8.0_171
```

**Comment by JadinAndrews** [comment]
@Aryess Thanks for your comment, I still had endless issues trying to get this to work under Windows 10, eventually gave up and tried on Ubuntu. 

So for those who find this, this is what I did:

Install ubuntu in a vm if you must.

:~$ sudo apt update

Install nvm (Node Version Manager)
:~$ wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash

:~$ nvm install 6.17.1
:~$ sudo apt install python
:~$ sudo apt install build-essential

And then you should be good to install ti_recover

:~$ npm install ti_recover

This worked for me.
